server:
  port: 21000 #工程端口
logging:
    level:
      root: info
    file:
      path: log
rtsp:
  enable: true
  proxy: false
websocket:
  enable: true
  proxy: false
spring:
  application:
    name: video-java
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        fail-fast: true